wandb_version: 1

model_name:
  desc: null
  value: eub7without2
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1722017654
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.7
      5: 0.17.0
      8:
      - 2
      - 5
      13: linux-x86_64
