_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 80
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.3
            "8":
                - 2
                - 5
            "12": 0.18.3
            "13": linux-x86_64
ds:
    value: breast_albumentation
model:
    value: eub3
